site_name: AWS Guide
theme:
    name: material
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue
        accent: blue
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: purple
        accent: purple
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

nav:
  - Home: index.md
  - Basics: 
        Infrastructure: aws-infra.md
        Models: models.md
        Billing: billing.md
  - Security:
      IAM: iam.md
      VPC: vpc.md
  - Interact with AWS Services:
      AWS CLI: cli.md
      Boto3: boto3.md
      Cloud9: cloud9.md
  - Compute:
      Intro: compute-intro.md
      EC2: compute-ec2.md
      Lambda: compute-lambda.md
      Containers: compute-containers.md
  - Storage:
      Intro: storage-intro.md
      S3: storage-s3.md
  - APIs:
      API Gateway: api-gateway.md
  - Step Functions: step-functions.md
  - Systems Manager: systems-manager.md
  - Monitoring:
      Cloudwatch: cloudwatch.md

repo_name: mapattacker/aws
repo_url: https://github.com/mapattacker/aws

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg